### ISSUE TITLE
Exception when download to directory doesn't already exist

### ISSUE THREAD

**Issue by dnezamfar** [sharkcooper/NomadParsing#10]
If you choose a directory that doesn't exist, the program will throw an exception. The directory structure should be created automatically as long as the user has permission to create it. If not, handle the access denied exception.

Download destination (full path): /Users/dnezamfar/NomadData
Traceback (most recent call last):
  File "NomadParse.py", line 9, in <module>
    os.chdir(user_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dnezamfar/NomadData'

**Comment by neemanejad** [comment]
After detecting that the user specified directory is incorrect or non-existent, the program should say `Invalid path, try again:` and allow the user to resubmit a path infinitely until the directory the user specifies exists on their machine. Is that what you meant by exception?

Or do you mean the program should create that specified path on the users machine when asked for a download location instead of checking if it exists?

**Comment by dnezamfar** [comment]
@sharkcooper If the user chooses a destination directory for the downloaded files that doesn't exist, create it automatically. Remember that we aren't prompting the user for anything in this program. It's all going to be passed in as command line arguments. https://docs.python.org/3.3/library/argparse.html

In my example in my comment, I chose /Users/dnezamfar/NomadData as my destination directory but the Python program threw an exception (an error condition) saying that "No such file or directory" exists. Because it didn't... /Users/dnezamfar, my home directory does, but not NomadData. Your program should create NomadData automatically if that's the destination the user chooses.

**Comment by dnezamfar** [comment]
You need to make sure that if the user chosen destination directory has other problems besides not existing, like a permission related issue, that you handle it and print what happened and exit.

For example, if I choose /Users/dnezmfar (mis-spelled home directory), your program will not have permission to create /Users/dnezmfar so it'll throw an exception and exit with some programmer friendly "permission denied". You should capture that exception and turn it into a more user friendly message saying something to the effect of "Could not create `< the directory name >`, check the permissions on this directory".

**Comment by neemanejad** [comment]
Alright, I'll cover that issue next.
