### ISSUE TITLE
Download files mulit-threaded to reduce total download duration

### ISSUE THREAD

**Issue by dnezamfar** [sharkcooper/NomadParsing#7]
Once you have the list of URL's that need to be downloaded, the time it takes to download each URL one by one (single-threaded) is expensive. There should be a way to batch download 10, 20, etc files at a time to dramatically improve the the time it takes to download an entire folder of data. The limitation isn't network bandwidth since these files are very small, it's the time it takes to initiate the HTTP Get request for each file, wait for it to download, save, and then move onto the next one.

A good example of a multi-threaded downloads that you can use is...
https://www.geeksforgeeks.org/simple-multithreaded-download-manager-in-python/

**Comment by neemanejad** [comment]
Resolved in [latest commit](https://github.com/sharkcooper/NomadParsing/commit/376b81643bafa89f8ce8cf6d0f1069adae53f492).
